apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: renovate/renovate:37.273.0@sha256:a9cee87b9bb968d639071fa2f807ccea8a29a20078426e676b83cde0b962d533
