apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: dmorina/gh-release-test:1.3.6-prod@sha256:76b23fb38f1a086b53241b0be0fc64ae7a6cae910797a36639b843a002dde1b8
