apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: renovate/renovate:34.28.1-slim@sha256:ab5149f5251090f590f6eb51cd7c9c1ef660c6ed5554e27c3749df166ad89165
