apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: renovate/renovate:37.87.2-slim@sha256:c04a54073032ba64a7e9bf6f98b910f173d7e983bae2058dbc987d4d02f4a046
