apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: renovate/renovate:35.159.5-slim@sha256:2a835b595b253f5ab994f4c5ad1231f5493ed5930c190650ab68b3bd7610844f
