apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: renovate/renovate:36.109.4-slim@sha256:93dfcaf0749b981b7272deb5487e5afcbf13505a4c2d237371ddfc6e402b73e1
