apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: renovate/renovate:32.241.11-slim@sha256:0e65ec8400bc8e1769b181576d001b0984934fcabe8bfd9b84dcd339c4052207
