apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: foo
          image: dmorina/github-release-test:1.3.5@sha256:7306b2d7371a9a93eb6bf3e71256d695152005bc7ab03c53d93ac35799be044e
